apiVersion: v1
kind: Service
metadata:
  name: cloud-major-assignment-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: cloud-assignment
  ports:
    - protocol: TCP
      port: 60000
      targetPort: 6000
      name: container1
    - protocol: TCP
      port: 60001
      targetPort: 6005
      name: container2