apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cloud-major-assignment-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi